#
# Makefile for the Blocks touchscreen drivers.
#

# Each configuration option enables a list of files.

fts_ts-y := focaltech_core.o focaltech_ctl.o focaltech_ex_fun.o \
            focaltech_gesture.o focaltech_flash.o

obj-$(CONFIG_TOUCHSCREEN_BLOCKS) += fts_ts.o 
